// react_site1/src/App.js
import React from "react";
import Header from "./components/layout/Header";
import Main from "./components/layout/Main";
import Footer from "./components/layout/Footer";
import Slider from "./components/section/Slider";
import Image from "./components/section/Image";
import ImgText from "./components/section/ImgText";
import Card from "./components/section/Card";
import Banner from "./components/section/Banner";
import Text from "./components/section/Text";

function App() {
  return (
    <>
      <Header fonts="nexon" />
      <Main>
        <Slider />
        <Image attr="section container nexon" />
        <ImgText attr={["section", "container", "nexon", "gray"]} />
        <Card attr={["section", "container", "nexon"]} />
        <Banner fonts="gmarket" />
        <Text attr={["section", "container", "nexon"]} />
      </Main>

      <Footer attr={["section", "container", "nexon", "gray"]} />
    </>
  );
}

export default App;

//

// vue_site2/src/App.vue
<template>
  <div>
      <HeaderLayout fonts="nexon" />
      <SliderSection fonts="nexon" />
      <ImageSection attr="section nexon" layout="container" />
      <ImgTextSection attr="section nexon gray" layout="container" />
      <CardSection attr="section nexon" layout="container" />
      <BannerSection fonts="gmarket" />
      <TextSection attr="section nexon" layout="container" />
      <FooterLayout attr="section nexon gray" layout="container" />
  </div>
</template>

<script>
import HeaderLayout from './components/layout/HeaderLayout.vue';
import FooterLayout from './components/layout/FooterLayout.vue';
import SliderSection from './components/section/SliderSection.vue';
import ImageSection from './components/section/ImageSection.vue';
import ImgTextSection from './components/section/ImgTextSection.vue';
import CardSection from './components/section/CardSection.vue';
import BannerSection from './components/section/BannerSection.vue';
import TextSection from './components/section/TextSection.vue';

export default{
  name: "App",
  components:{
      HeaderLayout,
      FooterLayout,
      SliderSection,
      ImageSection,
      ImgTextSection,
      CardSection,
      BannerSection,
      TextSection
  },
}
</script>
